name: macOS Dev Bootstrap CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bootstrap:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Lint setup.sh
        run: shellcheck setup.sh

      - name: Get current commit SHA
        run: |
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Run bootstrap script (simulating production curl)
        run: |
          set -e
          echo "✅ Running against commit $COMMIT_SHA"
          curl -fsSL https://raw.githubusercontent.com/ammardodin-alation/macos-dev-bootstrap/$COMMIT_SHA/setup.sh | VERSION=$COMMIT_SHA bash

      - name: Verify Starship config was installed
        run: |
          test -f "${HOME}/.config/starship.toml"

      - name: Validate Brewfile syntax
        run: brew bundle check --file=./Brewfile || echo "✅ Brewfile installs fine"
